[package]
name = "devnotes"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
clap = { version = "4.5.13", features = ["derive"] }
serde = { version = "1.0.205", features = ["derive"] }
toml = "0.8.19"
whoami = "1.5.1"
open = "5.3.0"
